"""
Django settings for alx_travel_app project.

Generated by 'django-admin startproject' using Django 5.2.3.
"""

import os
import logging
from pathlib import Path
import environ
from django.core.exceptions import ImproperlyConfigured

logger = logging.getLogger(__name__)

# BASE_DIR is where manage.py is located
BASE_DIR = Path(__file__).resolve().parent.parent

# --- ENVIRONMENT SETUP ---
env = environ.Env(
    DEBUG=(bool, False)
)

# Load .env file from same location as manage.py
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# --- SECURITY ---
SECRET_KEY = env("SECRET_KEY", default="django-insecure-unsafe-fallback-key")
DEBUG = env.bool("DEBUG", default=False)
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])

# --- APPLICATIONS ---
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "listings.apps.ListingsConfig",
    "corsheaders",
    "rest_framework",
    "drf_yasg",
]

# --- MIDDLEWARE ---
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "alx_travel_app.urls"

# --- TEMPLATES ---
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "alx_travel_app.wsgi.application"

# --- DATABASES (MySQL with SQLite fallback in DEBUG) ---
try:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": env("DB_NAME"),
            "USER": env("DB_USER"),
            "PASSWORD": env("DB_PASSWORD"),
            "HOST": env("DB_HOST", default="127.0.0.1"),
            "PORT": env("DB_PORT", default="3306"),
            "OPTIONS": {
                "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }
    logger.info(f"Using MySQL database: {env('DB_NAME')}")
except (ImproperlyConfigured, Exception) as e:
    if DEBUG:
        logger.warning(f"MySQL config failed: {e}. Falling back to SQLite (DEBUG mode).")
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": BASE_DIR / "db.sqlite3",
            }
        }
    else:
        raise  # 🚨 Fail hard in production

# --- PASSWORD VALIDATORS ---
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# --- INTERNATIONALIZATION ---
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# --- STATIC FILES ---
STATIC_URL = "static/"

# --- PRIMARY KEY FIELD TYPE ---
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# --- CORS ---
CORS_ALLOW_ALL_ORIGINS = True

# --- CELERY ---
CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="amqp://localhost")
CELERY_RESULT_BACKEND = "rpc://"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"

# --- PAYMENTS / KEYS ---
CHAPA_SECRET_KEY = env("CHAPA_SECRET_KEY", default="")
